"""Export case data to PDF format using weasyprint."""
import os
import logging

logger = logging.getLogger(__name__)

HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
body {{
    font-family: 'Noto Sans CJK SC', 'NotoSansCJK', 'WenQuanYi Micro Hei', sans-serif;
    font-size: 11pt;
    line-height: 1.8;
    color: #333;
    max-width: 800px;
    margin: 0 auto;
    padding: 40px;
}}
h1 {{
    text-align: center;
    color: #1a1a2e;
    border-bottom: 2px solid #16213e;
    padding-bottom: 10px;
    font-size: 22pt;
}}
h2 {{
    color: #16213e;
    border-left: 4px solid #0f3460;
    padding-left: 10px;
    margin-top: 25px;
    font-size: 14pt;
}}
h3 {{
    color: #333;
    font-size: 12pt;
    margin-top: 15px;
}}
.info-item {{
    margin: 5px 0;
}}
.info-label {{
    font-weight: bold;
    color: #16213e;
}}
.step-box {{
    background: #f8f9fa;
    border: 1px solid #dee2e6;
    border-radius: 6px;
    padding: 12px 16px;
    margin: 10px 0;
}}
.step-box .step-title {{
    font-weight: bold;
    color: #0f3460;
    margin-bottom: 8px;
}}
ul {{
    padding-left: 20px;
}}
li {{
    margin: 5px 0;
}}
.footer {{
    margin-top: 40px;
    text-align: center;
    color: #999;
    font-size: 9pt;
    border-top: 1px solid #eee;
    padding-top: 10px;
}}
</style>
</head>
<body>
<h1>{title}</h1>

<h2>基本信息</h2>
<div class="info-item"><span class="info-label">故障现象：</span>{fault_phenomenon}</div>
<div class="info-item"><span class="info-label">涉及设备/软件：</span>{equipment}</div>
<div class="info-item"><span class="info-label">故障时间：</span>{fault_time}</div>
<div class="info-item"><span class="info-label">处理人员：</span>{personnel}</div>

<h2>故障描述</h2>
<p>{fault_description}</p>

<h2>排障过程</h2>
{troubleshooting_html}

<h2>根因分析</h2>
<p>{root_cause}</p>

<h2>解决方案</h2>
<p>{solution}</p>

<h2>经验总结</h2>
{lessons_html}

<div class="footer">Generated by Chat Case to Doc</div>
</body>
</html>"""


def _build_troubleshooting_html(steps: list) -> str:
    if not steps:
        return "<p>未提及排查步骤</p>"
    html_parts = []
    for step in steps:
        html_parts.append(f"""
<div class="step-box">
    <div class="step-title">步骤 {step.get('step', '?')}</div>
    <div><span class="info-label">操作：</span>{step.get('action', '未提及')}</div>
    <div><span class="info-label">观察结果：</span>{step.get('observation', '未提及')}</div>
    <div><span class="info-label">分析判断：</span>{step.get('analysis', '未提及')}</div>
</div>""")
    return "\n".join(html_parts)


def _build_lessons_html(lessons: list) -> str:
    if not lessons:
        return "<p>未提及经验总结</p>"
    items = "\n".join(f"<li>{l}</li>" for l in lessons)
    return f"<ul>{items}</ul>"


def generate_pdf(case_data: dict, output_path: str) -> str:
    """Generate a PDF document from case data."""
    from weasyprint import HTML
    
    html_content = HTML_TEMPLATE.format(
        title=case_data.get("title", "排障案例"),
        fault_phenomenon=case_data.get("fault_phenomenon", "未提及"),
        equipment=case_data.get("equipment", "未提及"),
        fault_time=case_data.get("fault_time", "未提及"),
        personnel=case_data.get("personnel", "未提及"),
        fault_description=case_data.get("fault_description", "未提及"),
        troubleshooting_html=_build_troubleshooting_html(case_data.get("troubleshooting_steps", [])),
        root_cause=case_data.get("root_cause", "未提及"),
        solution=case_data.get("solution", "未提及"),
        lessons_html=_build_lessons_html(case_data.get("lessons_learned", [])),
    )
    
    HTML(string=html_content).write_pdf(output_path)
    logger.info(f"PDF saved to {output_path}")
    return output_path
